language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import markdown
script:
- make publish travis_github
env:
  global:
    secure: FILzyaNMqlcy8OHyVvjy0IxrlYQR630kb8FlSftD4wZcVgqN6LgK0Fw0b9Hpovn4S+1uQQ5sum+zFEjcp4V0JYSN6Tr+H3XX/Y+fbfkOdfcfHWyTSd5xYe5nwTBC1XuZHbiYWVBVqkavXOuMz+BTkdneZd8J8mDcKsxZy42rcML2rY6jeLAZVAWTRi+++Tm1hA/v3o3riaxT7S10aPEaKWzAeJSOmhIfATzFHjv/KAYixsnIBIv8bzylbpq+LlhIqDfaOsI7KTZUYqncSmn5Hovm/BR6FYeAGpyivsf+VCA40T2LWEHFyQdCN844N6NXMcvh9YL3Ddh1oqnMSBKeTx7LzGdYn5nn8d2HvF0KB2qaThtUVPyeTly/p/Rq5kwQK0rl6lWbG/fUuMKD3xjSVgkqDKu4Q+v0RFxnh/dXAP/FC+LEqajqI1KZw6NbuYub3wrahTeA47/OMYZH6uZO5lSzy4iFeojgvAhKFK13LsmwEDsEK28JgfManlJmu0cbrwpo56lEktc9YbJ0UsnJhdHDX5cpl2qiFtqW/T1bXX08DG6eNtXhYBhX5fnlE/GwWqDIg+kUqB1nFgPLGCLpCo8qgreejyNUKv0ekM0guuVPjVeho1Pr2RJfIH4LzUA1lYXZjDfCWlhOSh7KbJQN7yQjpmBnnGQtNMPANubyTnk=
